server:
  port: 6572

# LogBack(Log4j)
logging:
  level: ## LOGGING LEVEL : 1) ERROR 2) WARN 3) INFO 4) DEBUG 5) TRACE
    root: info
  pattern: ## 기본 로깅 패턴을 수정 합니다.
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%logger:){cyan}%clr(%M){blue}%clr(::%L){green} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
# swagger enable
springfox:
  documentation:
    swagger:
      v2:
        enabled: true
---
# --- profile local --- #
spring:
  config:
    activate:
      on-profile: local

# banner
banner:
  location: banner/local-banner.txt

---
# --- profile dev --- #
spring:
  config:
    activate:
      on-profile: dev
# banner
banner:
  location: banner/dev-banner.txt

---
# --- profile operation --- #
spring:
  config:
    activate:
      on-profile: op
# banner
banner:
  location: banner/op-banner.txt

