version: "3"
services:
  db:
    image: mariadb
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    container_name: mysql-favores-test # 컨테이너 이름 설정
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      - MARIADB_DATABASE=favores_web
      - MARIADB_ROOT_PASSWORD=vkqhfptm
      - TZ=Asia/Seoul
    volumes:
      - ./mariadb/data:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)